version: '2'

services:
  db:
    image: postgres:10-alpine
    restart: unless-stopped
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=postgres"
    volumes:
      - db-data:/var/lib/postgresql
      - ./scripts/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - local

volumes:
  db-data:
    driver: local

networks:
  local:
    driver: bridge
